# Generated by Django 3.1.7 on 2023-12-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_products_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
    ]
