# Generated by Django 3.1.7 on 2023-12-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_products_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(default='Shs', max_length=3),
        ),
    ]
